name: Main Pipeline

on:
  push:
    branches: [ "main", "Ava-branch" ]
  pull_request:
    branches: [ "main", "Ava-branch" ]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  MAIN_BRANCH: 'main'
  SAGE_DIR: '/usr/local/sage/SageV2'

jobs:

  node:
    uses: ./.github/workflows/node.js.yml

  #documentation step would go here but not ready yet
